
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  # Azure service connection established during pipeline creation
  serviceConnection: "sc-defender-report-prd"
  functionAppName: "vsad-p-defender-report-alfa"
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  displayName: "Setting Python version to 3.10 as required by functions"
  inputs:
    versionSpec: '3.10'
    architecture: 'x64'
- bash: |
    if [ -f extensions.csproj ]
    then
        dotnet build extensions.csproj --output ./bin
    fi
    pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    artifactName: 'drop'

#- task: AzureFunctionApp@2 # Add this at the end of your file
  #inputs:
    #azureSubscription: $(serviceConnection)
    #appType: functionAppLinux # default is functionApp
    #appName: $(functionAppName)
    #package: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'  #$(System.ArtifactsDirectory)/**/*.zip
    #deploymentMethod: 'auto' # 'auto' | 'zipDeploy' | 'runFromPackage'. Required. Deployment method. Default: auto.
    #Uncomment the next lines to deploy to a deployment slot
    #Note that deployment slots is not supported for Linux Dynamic SKU
    #deployToSlotOrASE: true
    #resourceGroupName: '<Resource Group Name>'
    #slotName: '<Slot name>'